multiconfigs.py: Update lopper xlnx overlay dt commands
1. Lopper tool xlnx_overlay_dt scripts commands has change, Hence
   update the same in sdt_flow.py
2. sdt_flow.py overlay feature was using lopper overlay for pl,
   Using lopper overlay with xlnx_overlay_dt scripts it doesn't remove
   pl device tree nodes from Linux dts. Hence change this from lopper
   overlay to xlnx_overlay_dt which is used to remove all the pl
   device tree nodes from linux device-tree during lopper operation.
3. Add new function RunLopperPlOverlaycommand instead of using
   RunLopperSubcommand as xlnx_overlay_dt operation requies additional
   argument for writing out to ps only dts file instead of overwriting
   the original SDT hw dts file.
4. Update lop-a78-imux.dts which is available in lopper now.
5. Fix below parse issue with pl-overlay, we need linux dts for with
   and without pl-overlay. Without <processor>-<soc-family>-linux.dts
   it fails to parse recipes.
   ERROR: /scratch/sandeep/yocto/2024.1/yp-dev/sources/poky/../meta-xilinx/meta-xilinx-core/recipes-bsp/device-tree/device-tree.bb: Unable to get checksum for device-tree SRC_URI entry cortexa53-zynqmp-linux.dts: file could not be found

Signed-off-by: Sandeep Gundlupet Raju <sandeep.gundlupet-raju@amd.com>

Acked-for-series: Raju Kumar Pothuraju <rajukumar.pothuraju@amd.com>