gen-machineconf: decode has been removed in python 3.10
str.decode('...') has been removed in python 3.10, this results in:

Traceback (most recent call last):
  File "/scratch2/mhatle/git/external/poky/build-new/../gen-machine-conf/gen-machineconf", line 439, in <module>
    ret = main()
  File "/scratch2/mhatle/git/external/poky/build-new/../gen-machine-conf/gen-machineconf", line 318, in main
    if line.decode('utf-8').startswith('XILINX_SDK_TOOLCHAIN'):
AttributeError: 'str' object has no attribute 'decode’

Work around the issue by capturing the exception and skipping the decode.

Signed-off-by: Mark Hatle <mark.hatle@amd.com>